version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: miapp
    volumes:
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
